package org.example;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class backpack_GUI {
    private JLabel numerOfItemsToGenerate_Label;
    private JTextField numerOfItemsToGenerate_TextField;
    private JLabel seed_Label;
    private JTextField seed_TextField;
    private JLabel capacity_Label;
    private JTextField capacity_TextField;
    private JButton start_Button;
    private JTextArea generatedItems_TextArea;
    private JTextArea packedItems_TextArea;
    private JPanel mainPanel;

    public backpack_GUI() {
        final Problem[] problem = new Problem[1];
        final Result[] result = new Result[1];
//        numerOfItemsToGenerate_TextField.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//
//            }
//        });

        start_Button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    int numberOfItems = Integer.parseInt(numerOfItemsToGenerate_TextField.getText());
                    int seed = Integer.parseInt(seed_TextField.getText());
                    int capacity = Integer.parseInt(capacity_TextField.getText());

                    if (numberOfItems <= 0 || capacity <= 0 || seed <= 0) {
                        JOptionPane.showMessageDialog(mainPanel, "Ilość elementów / pojemność plecaka / ziarno musi być większe niż 0.", "Input Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }

                    problem[0] = new Problem(numberOfItems, seed, 1, 10);
                    result[0] = problem[0].solve(capacity);

                    generatedItems_TextArea.setText(problem[0].toString());
                    packedItems_TextArea.setText(result[0].toString());


                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(mainPanel, "Please enter valid numbers.", "Input Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }

    public static void main(String[] args) {
        backpack_GUI gui = new backpack_GUI();
        JFrame frame = new JFrame("backpack_GUI");
        frame.setContentPane(gui.mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        mainPanel.setEnabled(true);
        mainPanel.setMinimumSize(new Dimension(300, 300));
        mainPanel.setPreferredSize(new Dimension(450, 400));
        final JScrollPane scrollPane1 = new JScrollPane();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        gbc.gridheight = 11;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(scrollPane1, gbc);
        packedItems_TextArea = new JTextArea();
        packedItems_TextArea.setEditable(false);
        packedItems_TextArea.setText("");
        scrollPane1.setViewportView(packedItems_TextArea);
        final JScrollPane scrollPane2 = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 12;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(scrollPane2, gbc);
        generatedItems_TextArea = new JTextArea();
        generatedItems_TextArea.setEditable(false);
        scrollPane2.setViewportView(generatedItems_TextArea);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 13;
        gbc.weighty = 0.05;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 10;
        gbc.weightx = 0.1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer6, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Spakowane przedmioty");
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.SOUTH;
        mainPanel.add(label1, gbc);
        capacity_TextField = new JTextField();
        capacity_TextField.setMinimumSize(new Dimension(60, 34));
        capacity_TextField.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(capacity_TextField, gbc);
        start_Button = new JButton();
        start_Button.setText("Start");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 10;
        gbc.gridwidth = 2;
        gbc.weighty = 0.05;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(start_Button, gbc);
        seed_TextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(seed_TextField, gbc);
        numerOfItemsToGenerate_TextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(numerOfItemsToGenerate_TextField, gbc);
        numerOfItemsToGenerate_Label = new JLabel();
        numerOfItemsToGenerate_Label.setText("Ilość przedmiotów do wygenerowania");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.SOUTH;
        mainPanel.add(numerOfItemsToGenerate_Label, gbc);
        seed_Label = new JLabel();
        seed_Label.setText("Ziarno");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.SOUTH;
        mainPanel.add(seed_Label, gbc);
        capacity_Label = new JLabel();
        capacity_Label.setText("Pojemność plecaka");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        mainPanel.add(capacity_Label, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Wygenerowane przedmioty");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 11;
        gbc.anchor = GridBagConstraints.SOUTH;
        mainPanel.add(label2, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 11;
        gbc.weightx = 0.1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer7, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weighty = 0.05;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer8, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
